=== rt-cpan/rt-cpan.github.io/Ticket/Attachment/679998/350024/metadata.dtd
<!ELEMENT metadata (acm_ccs?, author*, datatype*, faculty_member?, keyword*, lab?, pages?, publication_venue?, research_topic?, title?, year?)>
<!ELEMENT acm_ccs (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT datatype (#PCDATA)>
<!ELEMENT faculty_member (#PCDATA)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT lab (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT publication_venue (#PCDATA)>
<!ELEMENT research_topic (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== rt-cpan/rt-cpan.github.io/Ticket/Attachment/679998/350023/test.xml
<?xml version="1.0"?>
<!DOCTYPE metadata SYSTEM "metadata.dtd">
<metadata>
<acm_ccs>asdfasdf</acm_ccs>
<author>Trevor McLeod</author>
<author>Mike Brannigan</author>
<author>Ted Bessel</author>
<datatype>dt1</datatype>
<datatype>dt2</datatype>
<faculty_member>Dr. Beverly Crusher</faculty_member>
<keyword>kw1</keyword>
<keyword>kw2</keyword>
<lab>SPL</lab>
<pages>45</pages>
<publication_venue>UBC</publication_venue>
<research_topic>Some research topic</research_topic>
<title>Some title</title>
<year>2010</year>
</metadata>
